name: Auto-assign Issues to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign new issues and pull requests to project 1 Backlog
        uses: srggrs/assign-one-project-github-action@1.2.0
        with:
          project: 'https://github.com/floccusaddon/floccus/projects/1'
          column_name: 'Backlog'
